// generated by web/scripts/sync-shared.sh from src/report/enrich.ts — do not edit
// 리포트의 결정론 섹션 — "계산은 코드로, 해석만 AI로".
// 여기 문장은 LLM이 아니라 표에서 나온다. 제보 5문항의 선택지별 읽기, 질문별 판독 기준, 단계 로드맵, 상대 일간별 프로필·접근.
import { ARCHETYPES, type Archetype } from '../saju/archetypes.ts';
import { computeChart, type Gan } from '../saju/manse.ts';
import { computeCompat, type Compat } from '../saju/compat.ts';
import { SELF_QUESTIONS, scoreSelfReport, estimateStage, type SelfAnswers, type SelfQuestion, type Stage } from './selfreport.ts';
import type { QuestionKey } from './questions.ts';

/** 결정론 섹션 렌더에 필요한 문맥 — 데모(SkuResult)와 실제(서버 row) 양쪽에서 만든다 */
export interface ReportContext {
  question: QuestionKey;
  nickname: string;
  myArchetype: Archetype;
  theirArchetype: Archetype;
  compat: Compat;
  selfAnswers: SelfAnswers;
  signalIndex: number;
  flags: string[];
  stage: Stage;
}

/** 제보 5문항 × 선택지별 읽기 — 옵션 순서는 selfreport.ts의 SELF_QUESTIONS와 같아야 한다 */
export const SIGNAL_READINGS: Record<SelfQuestion['key'], string[]> = {
  reply: [
    '대화가 열려 있을 때 바로 반응하는 사람. 관심의 신호이거나 원래 답이 빠른 습관 — 다른 신호와 같이 봐.',
    '일상 안에서 네 연락에 우선순위가 있는 편. 무관심이면 이 리듬이 제일 먼저 무너져.',
    '대화를 몰아서 처리하는 리듬. 관심이 없다기보다 연락이 생활의 중심이 아닌 사람일 수 있어.',
    '리듬만 보면 낮은 우선순위. 단, 원래 느린 유형인지 상대의 결에서 같이 확인해.',
    '상대의 상황에 따라 흔들리는 리듬 — 마음보다 일정이 변수일 가능성. 늦어지는 때의 요일·시간을 봐.',
  ],
  initiate: [
    '시작의 힘이 한쪽에 있어. 상대가 받는 데 익숙해진 상태 — 실험으로 상대 쪽 힘을 확인해야 하는 이유야.',
    '네가 조금 더 움직이지만 상대도 시작해. 건강한 범위.',
    '가장 좋은 신호 중 하나. 관계를 같이 굴리는 중.',
    '상대가 더 움직이는 중. 네가 리듬을 늦춰도 관계가 유지되는지가 확인 포인트.',
    '상대의 관심이 행동으로 나오는 중. 네 쪽 반응이 관계의 속도를 정해.',
  ],
  meet: [
    '말보다 무거운 팩트. 상대가 시간을 만들었다는 건 우선순위 안에 네가 있다는 뜻.',
    '만남은 됐지만 시작은 너였어. 다음 만남 제안을 넘겨보면 상대 쪽 힘이 보여.',
    '단둘의 시간을 피하는 건지 계기가 없었던 건지 아직 몰라. 단둘 제안에 대한 반응이 갈림길.',
    '연락만으로는 관계가 굳지 않아. 2주 안에 만남이 없으면 리듬은 식기 쉬워.',
  ],
  last: [
    '관계가 살아 있는 구간. 지금 신호가 가장 정확해.',
    '정상 범위. 다음 만남이 잡히는지가 관건.',
    '리듬이 느슨해지는 경계. 이번 주에 만남 제안이 오가는지 봐.',
    '관계가 정체됐거나 연락 관계로 굳는 중. 판독보다 재시동 실험이 먼저.',
    '탐색 단계. 연락 리듬이 유일한 단서라 신호를 과하게 읽기 쉬워 — 실험으로 확인해.',
  ],
  theirs: [
    '상대가 먼저 움직인 기록이 없어. 관심이 없거나, 네가 먼저 채워서 상대가 움직일 틈이 없었거나 — 그래서 "먼저 연락 멈추기" 실험이 여기서 나와.',
    '가끔 움직여. 계기가 있을 때만인지 리듬이 생기는 중인지, 2주 더 보면 갈려.',
    '상대 쪽에서도 대화를 만들고 있어. 관심의 안정적인 신호.',
    '상대가 적극적이야. 네가 신호를 작게 읽고 있을 가능성 — 실제 단계가 판정보다 앞서 있을 수 있어.',
  ],
};

/** 질문별 판독 기준 — 어느 제보 항목이 이 질문의 핵심 증거인지 */
export const QUESTION_FOCUS: Record<QuestionKey, { keys: SelfQuestion['key'][]; rule: string }> = {
  interest: { keys: ['theirs', 'meet'], rule: '관심은 말이 아니라 상대가 먼저 만든 연락과 만남에서 읽어. 답장 속도는 보조 지표야.' },
  contact: { keys: ['reply', 'last'], rule: '연락해도 되는지는 마지막 접점과 답장 리듬이 정해. 텀이 길수록 가벼운 계기로 들어가.' },
  status: { keys: ['meet', 'initiate'], rule: '이름을 붙일 수 있는지는 단둘의 시간이 반복되는지, 시작의 힘이 양쪽에 있는지로 갈려.' },
  cooling: { keys: ['reply', 'theirs'], rule: '식은 건지 바쁜 건지는 답장 리듬의 변화와 상대가 먼저 움직인 기록으로 구분해.' },
  confess: { keys: ['meet', 'theirs'], rule: '고백 타이밍은 상대 제안 만남과 먼저 연락 기록이 같이 있을 때야. 한쪽만 있으면 실험이 먼저.' },
};

export const STAGE_ROADMAP: Record<Stage, { desc: string; next: string; condition: string }> = {
  관심: { desc: '서로 알고 연락은 있지만 단둘의 시간은 아직 없는 구간.', next: '만남', condition: '단둘이 보자는 제안이 어느 쪽에서든 나오고 실제로 성사되는 것.' },
  만남: { desc: '단둘의 시간은 있었지만 리듬이 굳지 않은 구간.', next: '관계', condition: '만남이 반복되고 다음 약속이 자연스럽게 잡히는 것 — 특히 상대 쪽 제안으로.' },
  관계: { desc: '만남과 연락이 이어지는 중. 이름을 붙이지 않았을 뿐.', next: '결단', condition: '관계에 이름을 붙일지 말지, 서로의 의사가 말이나 행동으로 확인되는 것.' },
  결단: { desc: '이름을 붙일지 정하는 구간.', next: '고백 또는 정리', condition: '실험 결과가 선택을 대신 말해줘. 신호가 확인되면 말로 옮길 차례.' },
  정리: { desc: '신호가 낮고 식음이 확인되는 구간.', next: '회복', condition: '판독을 멈추고 거리와 회복이 먼저. 3주 뒤 다시 봐.' },
};

/** 상대 일간별 — 관심이 있을 때 흔한 움직임 / 없을 때 흔한 움직임. 단정이 아니라 판독 기준. */
export const THEIR_PROFILE: Record<Gan, { on: string; off: string }> = {
  甲: { on: '먼저 움직여. 약속을 직접 잡고 돌려 말하지 않아 — 있으면 있는 티가 나는 유형.', off: '반응이 짧아지고 방향을 바꾸지 않아. 애매하게 끄는 법이 없어서, 미지근함이 길면 그게 답이야.' },
  乙: { on: '네 일정과 취향에 맞춰주고 대화가 끊기지 않게 이어가. 티는 적은데 지속돼.', off: '맞춰주는 태도는 그대로인데 단둘의 시간을 만들지 않아. 친절이 곧 관심은 아닌 유형.' },
  丙: { on: '표정·말·연락 전부에 티가 나. 리액션이 크고 먼저 연락하는 횟수가 눈에 띄게 늘어.', off: '온도가 눈에 띄게 떨어져. 이 유형에겐 미지근함 자체가 답이라, 애매한 중간은 드물어.' },
  丁: { on: '네가 한 말을 기억하고 되물어. 밤 시간대에 대화가 길어지고 사소한 걸 챙겨.', off: '예의 바르고 짧은 답. 되묻는 질문이 사라지면 마음이 빠진 신호야.' },
  戊: { on: '표현은 없는데 자리를 지켜. 같은 자리에 계속 나타나고 부탁을 들어줘 — 말 대신 곁으로 말하는 유형.', off: '갈등 없이 거리만 생겨. 조용히 빠지기 때문에 눈치채기 어려워.' },
  己: { on: '챙겨. 밥 먹었는지, 잘 들어갔는지 같은 실용적인 돌봄이 늘어.', off: '챙김이 예의 수준으로 줄고 네 부탁에 조건이 붙어. 기준을 넘으면 한 번에 선을 그어.' },
  庚: { on: '직설적으로 묻고 날짜를 박아. 애매한 관계를 오래 두지 않아.', off: '빠르게 선을 그어. 여지를 안 남겨서 오히려 명확한 유형.' },
  辛: { on: '네 말의 디테일을 기억하고, 인정하는 말에 반응해. 티 안 나게 재는 중.', off: '말투가 차가워지고 거리를 둬. 서운함을 말하지 않고 쌓는 편이라 이유를 알기 어려워.' },
  壬: { on: '분위기를 맞춰주고 대화가 편해져. 단둘의 자리를 피하지 않지만 결정적인 말은 늦어.', off: '흐름은 맞춰줘도 단둘의 시간을 만들지 않아. 편한데 진전이 없으면 이쪽이야.' },
  癸: { on: '네 기분을 먼저 살피고 조용히 챙겨. 먼저 연락은 적어도 답은 성실해.', off: '답이 짧아지고 네 기분을 살피는 질문이 사라져. 혼자 정리하는 유형이라 통보가 늦어.' },
};

/** 상대 일간별 — 이 사람에게 통하는 접근 */
export const APPROACH: Record<Gan, string> = {
  甲: '돌려 말하기보다 명확한 반응이 통해. 애매하게 재는 태도엔 빨리 식어.',
  乙: '부딪히지 않고 맞춰주는 사람에게 스며들어. 급하게 밀면 물러나.',
  丙: '밝은 리액션에 마음이 열려. 미지근한 반응은 관심 없음으로 읽어버려.',
  丁: '작은 말투 하나도 오래 기억해. 일관된 다정함이 통하고, 들쭉날쭉한 온도엔 혼자 시나리오를 써.',
  戊: '빠른 확답을 요구하면 굳어. 곁에 오래 있는 방식으로 다가가야 열려.',
  己: '챙김을 알아주는 사람에게 열려. 당연하게 받으면 어느 날 선을 그어.',
  庚: '애매함을 오래 못 참아. 결론이 있는 대화, 날짜가 있는 약속이 통해.',
  辛: '무심한 한마디에 오래 상처받아. 인정과 세심한 반응이 통해.',
  壬: '말보다 흐름을 봐. 확신이 설 때까지 결론을 미루니 재촉보다 꾸준함이 통해.',
  癸: '눈치가 빨라서 진심이 아니면 알아채. 조용히 꾸준한 표현이 통해.',
};

export interface SignalRow {
  key: SelfQuestion['key'];
  label: string;
  answer: string;
  value: number;
  reading: string;
  /** 이 질문의 핵심 증거 항목 */
  focus: boolean;
}

export function signalRows(answers: SelfAnswers, question: QuestionKey): SignalRow[] {
  const focus = QUESTION_FOCUS[question].keys;
  return SELF_QUESTIONS.flatMap((q) => {
    const i = answers[q.key];
    if (i === undefined) return [];
    const opt = q.options[i];
    return [{ key: q.key, label: q.label, answer: opt.label, value: opt.value, reading: SIGNAL_READINGS[q.key][i] ?? '', focus: focus.includes(q.key) }];
  });
}

export function buildContext(args: {
  question: QuestionKey; nickname: string; myChart: { dayGan: Gan }; theirChart: { dayGan: Gan }; compat: Compat;
  selfAnswers: SelfAnswers; signalIndex: number; flags: string[]; stage: Stage;
}): ReportContext {
  return {
    question: args.question, nickname: args.nickname,
    myArchetype: ARCHETYPES[args.myChart.dayGan], theirArchetype: ARCHETYPES[args.theirChart.dayGan],
    compat: args.compat, selfAnswers: args.selfAnswers, signalIndex: args.signalIndex, flags: args.flags, stage: args.stage,
  };
}

/** `?demo=report`용 문맥 — SAMPLE_REPORT(壬 × 己, '나한테 관심 있는 걸까?')와 같은 시나리오 */
export function sampleContext(): ReportContext {
  const my = computeChart({ year: 1999, month: 3, day: 11, hour: 6, minute: 30, calendar: 'solar' }); // 壬戌일
  const their = computeChart({ year: 1996, month: 6, day: 11, hour: null, minute: 0, calendar: 'solar' }); // 己卯일
  const answers: SelfAnswers = { reply: 1, initiate: 1, meet: 0, last: 1, theirs: 1 };
  const sr = scoreSelfReport(answers);
  return buildContext({
    question: 'interest', nickname: '걔', myChart: my, theirChart: their, compat: computeCompat(my, their),
    selfAnswers: answers, signalIndex: sr.signalIndex, flags: sr.flags, stage: estimateStage(sr, 'interest').current,
  });
}
