#!/usr/bin/env bash
# web/src의 결정론 모듈(만세력·궁합·셀프리포트·스키마)을 Edge Functions 공유 폴더로 복사한다.
# Deno용으로 상대 import에 .ts 확장자를 붙이고 lunar-javascript를 npm 지정자로 바꾼다. 원본만 수정할 것.
set -e
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$ROOT/../supabase/functions/_shared"
mkdir -p "$DEST/saju" "$DEST/report"
conv() {
  { echo "// generated by web/scripts/sync-shared.sh from $2 — do not edit"; \
    sed -e "s#from 'lunar-javascript'#from 'npm:lunar-javascript@1.6.12'#" \
        -e "s#from '\./\([a-zA-Z]*\)'#from './\1.ts'#g" \
        -e "s#from '\.\./saju/\([a-zA-Z]*\)'#from '../saju/\1.ts'#g" "$ROOT/$2"; } > "$1"
}
for f in manse compat archetypes; do conv "$DEST/saju/$f.ts" "src/saju/$f.ts"; done
for f in questions selfreport schema timing enrich; do conv "$DEST/report/$f.ts" "src/report/$f.ts"; done
echo "synced → $DEST"
